-- MySQL Script generated by MySQL Workbench
-- mar 04 oct 2022 18:40:22
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Portfolio
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Portfolio
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Portfolio` DEFAULT CHARACTER SET utf8 ;
USE `Portfolio` ;

-- -----------------------------------------------------
-- Table `Portfolio`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Portfolio`.`usuarios` (
  `id_usuario` INT NOT NULL,
  `usuario` VARCHAR(45) NOT NULL,
  `password` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`id_usuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Portfolio`.`experiencias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Portfolio`.`experiencias` (
  `id_experiencia` INT NOT NULL,
  `experiencia_img` VARCHAR(80) NOT NULL,
  `sobre_experiencia` MEDIUMTEXT NOT NULL,
  `usuario_id_usuario` INT NOT NULL,
  PRIMARY KEY (`id_experiencia`, `usuario_id_usuario`),
  INDEX `fk_experiencia_usuario_idx` (`usuario_id_usuario` ASC) VISIBLE,
  CONSTRAINT `fk_experiencia_usuario`
    FOREIGN KEY (`usuario_id_usuario`)
    REFERENCES `Portfolio`.`usuarios` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Portfolio`.`actividades`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Portfolio`.`actividades` (
  `id_actividad` INT NOT NULL,
  `actividad` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_actividad`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Portfolio`.`educacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Portfolio`.`educacion` (
  `id_educacion` INT NOT NULL,
  `titulo_educacion` VARCHAR(45) NULL,
  `educacion_imagen` VARCHAR(80) NULL,
  `sobre_educacion` MEDIUMTEXT NULL,
  `usuario_id_usuario` INT NOT NULL,
  PRIMARY KEY (`id_educacion`, `usuario_id_usuario`),
  INDEX `fk_educacion_usuario1_idx` (`usuario_id_usuario` ASC) VISIBLE,
  CONSTRAINT `fk_educacion_usuario1`
    FOREIGN KEY (`usuario_id_usuario`)
    REFERENCES `Portfolio`.`usuarios` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Portfolio`.`acercaDe`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Portfolio`.`acercaDe` (
  `id_acercaDe` INT NOT NULL,
  `nombre_usuario` VARCHAR(45) NOT NULL,
  `apellido_usuario` VARCHAR(45) NOT NULL,
  `imagen_perfil` VARCHAR(80) NOT NULL,
  `sobre_usuario` MEDIUMTEXT NOT NULL,
  `ocupacion` VARCHAR(200) NOT NULL,
  `usuario_id_usuario` INT NOT NULL,
  PRIMARY KEY (`id_acercaDe`, `usuario_id_usuario`),
  INDEX `fk_acercaDe_usuario1_idx` (`usuario_id_usuario` ASC) VISIBLE,
  CONSTRAINT `fk_acercaDe_usuario1`
    FOREIGN KEY (`usuario_id_usuario`)
    REFERENCES `Portfolio`.`usuarios` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Portfolio`.`proyectos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Portfolio`.`proyectos` (
  `id_proyectos` INT NOT NULL,
  `titulo` VARCHAR(60) NOT NULL,
  `usuario_id_usuario` INT NOT NULL,
  PRIMARY KEY (`id_proyectos`, `usuario_id_usuario`),
  INDEX `fk_proyectos_usuario1_idx` (`usuario_id_usuario` ASC) VISIBLE,
  CONSTRAINT `fk_proyectos_usuario1`
    FOREIGN KEY (`usuario_id_usuario`)
    REFERENCES `Portfolio`.`usuarios` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Portfolio`.`imagenes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Portfolio`.`imagenes` (
  `id_imagen` INT NOT NULL,
  `imagen` VARCHAR(80) NOT NULL,
  PRIMARY KEY (`id_imagen`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Portfolio`.`tareas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Portfolio`.`tareas` (
  `actividades_id_actividad` INT NOT NULL,
  `experiencia_id_experiencia` INT NOT NULL,
  `experiencia_usuario_id_usuario` INT NOT NULL,
  PRIMARY KEY (`actividades_id_actividad`, `experiencia_id_experiencia`, `experiencia_usuario_id_usuario`),
  INDEX `fk_actividades_has_experiencia_experiencia1_idx` (`experiencia_id_experiencia` ASC, `experiencia_usuario_id_usuario` ASC) VISIBLE,
  INDEX `fk_actividades_has_experiencia_actividades1_idx` (`actividades_id_actividad` ASC) VISIBLE,
  CONSTRAINT `fk_actividades_has_experiencia_actividades1`
    FOREIGN KEY (`actividades_id_actividad`)
    REFERENCES `Portfolio`.`actividades` (`id_actividad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_actividades_has_experiencia_experiencia1`
    FOREIGN KEY (`experiencia_id_experiencia` , `experiencia_usuario_id_usuario`)
    REFERENCES `Portfolio`.`experiencias` (`id_experiencia` , `usuario_id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Portfolio`.`imgsProyectos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Portfolio`.`imgsProyectos` (
  `imagenes_id_imagen` INT NOT NULL,
  `proyectos_id_proyectos` INT NOT NULL,
  `proyectos_usuario_id_usuario` INT NOT NULL,
  PRIMARY KEY (`imagenes_id_imagen`, `proyectos_id_proyectos`, `proyectos_usuario_id_usuario`),
  INDEX `fk_imagenes_has_proyectos_proyectos1_idx` (`proyectos_id_proyectos` ASC, `proyectos_usuario_id_usuario` ASC) VISIBLE,
  INDEX `fk_imagenes_has_proyectos_imagenes1_idx` (`imagenes_id_imagen` ASC) VISIBLE,
  CONSTRAINT `fk_imagenes_has_proyectos_imagenes1`
    FOREIGN KEY (`imagenes_id_imagen`)
    REFERENCES `Portfolio`.`imagenes` (`id_imagen`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_imagenes_has_proyectos_proyectos1`
    FOREIGN KEY (`proyectos_id_proyectos` , `proyectos_usuario_id_usuario`)
    REFERENCES `Portfolio`.`proyectos` (`id_proyectos` , `usuario_id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
